### ISSUE TITLE
rest API exceeded request rate - code 102 - NSX-T Provider v 2.1.0

### ISSUE THREAD

**Issue by mdegrasse** [terraform-providers/terraform-provider-nsxt#404]
Getting many  Client 'admin' exceeded request rate of 100 per second (code 102)

i tried modifying the provider to add 102 as retry status codes but get same issue

happens randomly. Can fail for 2-3 mins then all good.

provider "nsxt" {
  host                  = var.nsx_manager
  username              = var.nsx_username
  password              = var.nsx_password
  allow_unverified_ssl  = true
  max_retries           = 100
  retry_min_delay       = 1000
  retry_max_delay       = 5000
  retry_on_status_codes = [429,102]
}

**Comment by waza-ari** [comment]
I have exactly the same problem and am not sure how to proceed from here.

**Comment by mdegrasse** [comment]
just realized this is same issue as #189 

I will try bumping up min delay and max delay.

TIA

**Comment by waza-ari** [comment]
@mdegrasse thanks for your feedback. Just wondering, ypou tried that according to your listing above. I also tried it, this didn't really change a thing. I believe this issue is still valid.

**Comment by mdegrasse** [comment]
lol sorry, was going to test and clicked the close issue by mistake instead of comment

**Comment by tvigneron** [comment]
From the platform side:
The NSX-T API service has three settings that control the rate of incoming API requests:

1) A per-client rate limit, in requests per second. If a client makes more requests than this limit in one second, the API server will refuse to service the API request and will return an HTTP 429 Too Many Requests Error. By default, this limit is 100 requests per second.

2) A per-client concurrency limit. This is the maximum number of outstanding requests that a client can have. For example, a client can open multiple connections to NSX-T and submit operations on each connection. When this limit is exceeded, the server returns a 429 Too Many Requests error to the client. By default, this limit is 40 concurrent requests.

3) An overall maximum number of concurrent requests. This is the maximum number of API requests that can be in process on the server. If the server is at this limit, additional requests will be refused and the HTTP error 503 Service Unavailable will be returned to the client. By default, this limit is 199 concurrent requests.

The first two limits are here to implement fairness between customers while the last protect the platform. The last limit is not user configurable but the first two are (so if they do not map to your usage you can change them, for instance you have one single client doing the calls. - one client = one account for NSX-T)/

In addition those limits are per NSX-T Manager so load balancing accross the 3 managers increase this :https://communities.vmware.com/docs/DOC-39390

**Comment by mdegrasse** [comment]
You forgot one important line from the NSX-T API documentation:

While it is possible to configure these rate limits using the /api/v1/node/services/http API, it is not recommended. Instead, **you should design your API client to gracefully deal with situations where limits are exceeded**.

So the provider should be able to handle this situation in my opinion.

**Comment by tvigneron** [comment]
@mdegrasse no objection there.
What the API guide is saying is that removing the limits should not replace having a clean automation on top. There is something we must look into here as Terraform should manage the different codes and retry. 

Now having said that, the per client limits are here for fairness between clients of the platform, and while there is a default those were left user-configurable as it might not match to all usage. 
From experience in environment with limited number of accounts doing a lot of API calls it can be advantageous to relax the limit (particularly the # of API calls) because you throttle it needlessly. (Think for example the extreme use-case of an environment with one single client doing the calls for everybody like a CMP.). 
Fairness depends on your consumption pattern, so if you have this issue regularly it can make sense to tune it to your environment and increase it makes sense.  (Waza-ari gave the cli to disable it but you can just increase too)
I will circle back to have this sentence on the API guide to be more precise.

In terms of workaround without changing anything in the platform:
-  Load balancing between the 3 managers. Generally I'd recommend this for people (in any case) doing a good level of automation as it improves both performance and resiliency.
-  @annakhm was telling me that you can adjust the level of parallelism Terraform does. I'll let her come back on this

My last point which is load balancing between the manager is also a good way to scale up and increases resiliency.

**Comment by mdegrasse** [comment]
@tvigneron Agreed. Load balancing the managers is in our design but not configured yet.

Currently, the nsx managers are not in production and the only client api calls are the ones i am doing with terraform bringing up the configs.

As troubleshooting steps, i tried to switch managers when i got the api call limit and got the same error.

I will try to drop the parallelism down to 5 and lower and report back.

-parallelism=n - Limit the number of concurrent operation as Terraform walks the graph. Defaults to 10.

**Comment by mdegrasse** [comment]
Happy to report that dropping the parallelism from 10 to 3 gives consistant positive results.

terraform plan -parallelism=3

Anything over 3 and i get random api exceeded errors. 

This is acceptable for me as a solution.

**Comment by waza-ari** [comment]
Hey. While I believe this can act as a workaround, its just a workaround for me. At the very least I feel it should be documented somewhere :)
